logging:
  level:
    web: DEBUG
spring:
  main:
    stacktrace-capacity: 4m
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/sampledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: voctionary@gmail.com
    password: xglowugsrjxukkac
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000